modLoader="javafml"
loaderVersion="[45,)"
license="Not specified"

[[mods]]
modId="ecolithica"
version="1.0.0"
displayName="Ecolithica"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Terrariandy and Footsore"
description="he he he ha"

[[dependencies.ecolithica]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"



[[dependencies.ecolithica]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

